### PR TITLE
feat: Basic AKS cluster + Vnet

### PR DESCRIPTION
**Pull request by chrismellard**
Stands up a basic RBAC enabled AKS cluster in a Vnet. Sensible defaults picked for all input variables if not supplied.

### CODE REVIEW

**Comment by hferentschik** [comment]
@chrismellard, awesome thanks. Looking good. Any chance you could update the README with some information on how to use this? 

It would be great if you could also update the commit message to follow the conventional commit message format? We are using this format, amongst other things,  to create changelogs - see https://jenkins-x.io/community/code/#the-commit-message
But that's something we can sort out for you if you prefer.

**Comment by chrismellard** [comment]
Sure thing. There are a few more things I want to throw in before merge so I'll mark as WIP. I'll update Readme as part of the remainder of the work.

**Comment by hferentschik** [comment]
> There are a few more things I want to throw in before merge so I'll mark as WIP. 

Looking already great. Looking forward to taking this to a spin. Pretty sure there will be a fair bit to do on the `jx` side as well. But at least we have a place to start from soon :-)

> I'll update Readme as part of the remainder of the work.

Let me know when you think you have something we should merge. This will form the base from where we can create dedicated issues addressing the things we discover need changing. Unless it would all just work out of the box :stuck_out_tongue_winking_eye:

**Comment by chrismellard** [comment]
Might be a good time to merge now after someone can reproduce a successful cluster creation. Working on producing a jx-requirements file that will be ready in a short while so I can start testing out the `jx` side of things. I spent some time on this last year before I had to put it down and there was plenty that broke in `jx` for sure - be interested to see what's changed ;)

**Comment by hferentschik** [comment]
I'll give cluster creation a go ...

**Comment by chrismellard** [comment]
Just added `jx-requirements` output. I'm done with this PR for now in terms of scope and will await feedback on it.

**Comment by hferentschik** [comment]
I am trying to create a cluster, but I am not sure what tp provide for all the variables I get asked for:

```
var.apex_domain
  Enter a value:

var.apex_domain_resource_group_name
  Enter a value:

var.cluster_name
  Enter a value: my-aks

var.cluster_resource_group
  Enter a value:

var.cluster_version
  Enter a value:

var.dns_prefix
  Enter a value:

var.dns_resource_group
  Enter a value:

var.domain_name
  Enter a value:

var.location
  Enter a value:

var.network_name
  Enter a value:

var.network_resource_group
  Enter a value:

var.node_count
  Enter a value:

var.node_size
  Enter a value:

var.subnet_cidr
  Enter a value:

var.subnet_name
  Enter a value:

var.vnet_cidr
  Enter a value:
```

What is the minimum amount of variables I need to specify to get a cluster up?

**Comment by chrismellard** [comment]
@hferentschik You can specify no inputs and the cluster creation will pick sensible defaults. If you check the README out you'll see they're all marked as optional inputs

**Comment by hferentschik** [comment]
@chrismellard, I got a bit further now. Here are some of my findings.

- I can see that defaulted in `local.tf`, but I am not sure whether all defaults are covered. I ended up commenting out the _dns_ module and _local_file_ resource. Then I got a bit further
- On that note, I think the defaulting should happen in `variables.tf`. For example:
    ```terraform
     variable "cluster_version" {
        description = "Kuberenetes version of the cluster"
        type    = string
        default = "1.15.11"
    }
    ```
    This way the variables are also documented and we can generate the in- and output tables. Any specific reason you do it in `local.tf`?
- When the listing finally worked and I executed the plan for the first time I got:
    ```
    $ terraform plan
    Refreshing Terraform state in-memory prior to plan...
    The refreshed state will be used to calculate this plan, but will not be
    persisted to local or remote state storage.
    
    
    ------------------------------------------------------------------------
    
    Error: Error ensuring Resource Providers are registered.
    
    Terraform automatically attempts to register the Resource Providers it supports to
    ensure it's able to provision resources.
    
    If you don't have permission to register Resource Providers you may wish to use the
    "skip_provider_registration" flag in the Provider block to disable this functionality.
    
    Please note that if you opt out of Resource Provider Registration and Terraform tries
    to provision a resource from a Resource Provider which is unregistered, then the errors
    may appear misleading - for example:
    
    > API version 2019-XX-XX was not found for Microsoft.Foo
    
    Could indicate either that the Resource Provider "Microsoft.Foo" requires registration,
    but this could also indicate that this Azure Region doesn't support this API version.
    
    More information on the "skip_provider_registration" flag can be found here:
    https://www.terraform.io/docs/providers/azurerm/index.html#skip_provider_registration
    
    Original Error: Cannot register provider Microsoft.DBforMariaDB with Azure Resource Manager:     resources.ProvidersClient#Register: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure:     Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client     'hferentschik@cloudbees.onmicrosoft.com' with object id '6bf2e421-2794-472e-a74f-29676d011bde' does not have     authorization to perform action 'Microsoft.DBforMariaDB/register/action' over scope '/subscriptions/    0ee859ed-0f8b-45c0-b61c-011a254f5736' or the scope is invalid. If access was recently granted, please refresh your     credentials.".
    
      on ../../../work/terraform/terraform-azurerm-jx/main.tf line 12, in provider "azurerm":
      12: provider "azurerm" {
    ```
    I ended up adding the `skip_provider_registration` to the provider configuration and that seems to have worked:
    ```terraform
    provider "azurerm" {
      version = ">= 2.15.0"
      features {}
      skip_provider_registration = true
   }
    ```

After fiddling around a bit and hacking my way around the issues above I got an initial plan:

```sh
$ terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

module.aks-jx.random_pet.dns_prefix: Refreshing state... [id=tf-jx-epic-raptor]
module.aks-jx.random_pet.domain_name: Refreshing state... [id=tf-jx-well-hookworm]
module.aks-jx.random_pet.subnet_name: Refreshing state... [id=tf-jx-magnetic-pug]
module.aks-jx.random_pet.cluster: Refreshing state... [id=tf-jx-included-macaque]
module.aks-jx.random_pet.network_resource_group: Refreshing state... [id=tf-jx-pleasant-caribou]
module.aks-jx.random_pet.network_name: Refreshing state... [id=tf-jx-verified-crappie]
module.aks-jx.random_pet.cluster_resource_group: Refreshing state... [id=tf-jx-smooth-polliwog]
module.aks-jx.random_pet.dns_resource_group: Refreshing state... [id=tf-jx-nice-mollusk]

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # module.aks-jx.azurerm_resource_group.cluster will be created
  + resource "azurerm_resource_group" "cluster" {
      + id       = (known after apply)
      + location = "australiaeast"
      + name     = "tf-jx-smooth-polliwog"
    }

  # module.aks-jx.azurerm_resource_group.network will be created
  + resource "azurerm_resource_group" "network" {
      + id       = (known after apply)
      + location = "australiaeast"
      + name     = "tf-jx-pleasant-caribou"
    }

  # module.aks-jx.module.cluster.azurerm_kubernetes_cluster.aks will be created
  + resource "azurerm_kubernetes_cluster" "aks" {
      + dns_prefix              = "tf-jx-epic-raptor"
      + fqdn                    = (known after apply)
      + id                      = (known after apply)
      + kube_admin_config       = (known after apply)
      + kube_admin_config_raw   = (sensitive value)
      + kube_config             = (known after apply)
      + kube_config_raw         = (sensitive value)
      + kubelet_identity        = (known after apply)
      + kubernetes_version      = "1.15.11"
      + location                = "australiaeast"
      + name                    = "hardy-aks-test"
      + node_resource_group     = (known after apply)
      + private_cluster_enabled = (known after apply)
      + private_fqdn            = (known after apply)
      + private_link_enabled    = (known after apply)
      + resource_group_name     = "tf-jx-smooth-polliwog"
      + sku_tier                = "Free"

      + addon_profile {
          + aci_connector_linux {
              + enabled     = (known after apply)
              + subnet_name = (known after apply)
            }

          + azure_policy {
              + enabled = (known after apply)
            }

          + http_application_routing {
              + enabled                            = (known after apply)
              + http_application_routing_zone_name = (known after apply)
            }

          + kube_dashboard {
              + enabled = (known after apply)
            }

          + oms_agent {
              + enabled                    = (known after apply)
              + log_analytics_workspace_id = (known after apply)
              + oms_agent_identity         = (known after apply)
            }
        }

      + auto_scaler_profile {
          + balance_similar_node_groups      = (known after apply)
          + max_graceful_termination_sec     = (known after apply)
          + scale_down_delay_after_add       = (known after apply)
          + scale_down_delay_after_delete    = (known after apply)
          + scale_down_delay_after_failure   = (known after apply)
          + scale_down_unneeded              = (known after apply)
          + scale_down_unready               = (known after apply)
          + scale_down_utilization_threshold = (known after apply)
          + scan_interval                    = (known after apply)
        }

      + default_node_pool {
          + max_pods             = (known after apply)
          + name                 = "default"
          + node_count           = 1
          + orchestrator_version = (known after apply)
          + os_disk_size_gb      = (known after apply)
          + type                 = "VirtualMachineScaleSets"
          + vm_size              = "Standard_B2ms"
          + vnet_subnet_id       = (known after apply)
        }

      + identity {
          + principal_id = (known after apply)
          + tenant_id    = (known after apply)
          + type         = "SystemAssigned"
        }

      + network_profile {
          + dns_service_ip     = (known after apply)
          + docker_bridge_cidr = (known after apply)
          + load_balancer_sku  = "Basic"
          + network_plugin     = "kubenet"
          + network_policy     = (known after apply)
          + outbound_type      = "loadBalancer"
          + pod_cidr           = (known after apply)
          + service_cidr       = (known after apply)

          + load_balancer_profile {
              + effective_outbound_ips    = (known after apply)
              + idle_timeout_in_minutes   = (known after apply)
              + managed_outbound_ip_count = (known after apply)
              + outbound_ip_address_ids   = (known after apply)
              + outbound_ip_prefix_ids    = (known after apply)
              + outbound_ports_allocated  = (known after apply)
            }
        }

      + role_based_access_control {
          + enabled = true

          + azure_active_directory {
              + managed   = true
              + tenant_id = (known after apply)
            }
        }

      + windows_profile {
          + admin_password = (sensitive value)
          + admin_username = (known after apply)
        }
    }

  # module.aks-jx.module.cluster.kubernetes_namespace.jenkins_x_namespace will be created
  + resource "kubernetes_namespace" "jenkins_x_namespace" {
      + id = (known after apply)

      + metadata {
          + generation       = (known after apply)
          + name             = "jx"
          + resource_version = (known after apply)
          + self_link        = (known after apply)
          + uid              = (known after apply)
        }
    }

  # module.aks-jx.module.vnet.azurerm_subnet.cluster_subnet will be created
  + resource "azurerm_subnet" "cluster_subnet" {
      + address_prefix                                 = (known after apply)
      + address_prefixes                               = [
          + "10.8.0.0/24",
        ]
      + enforce_private_link_endpoint_network_policies = false
      + enforce_private_link_service_network_policies  = false
      + id                                             = (known after apply)
      + name                                           = "tf-jx-magnetic-pug"
      + resource_group_name                            = "tf-jx-pleasant-caribou"
      + virtual_network_name                           = "tf-jx-verified-crappie"
    }

  # module.aks-jx.module.vnet.azurerm_virtual_network.cluster will be created
  + resource "azurerm_virtual_network" "cluster" {
      + address_space       = [
          + "10.8.0.0/16",
        ]
      + guid                = (known after apply)
      + id                  = (known after apply)
      + location            = "australiaeast"
      + name                = "tf-jx-verified-crappie"
      + resource_group_name = "tf-jx-pleasant-caribou"
      + subnet              = (known after apply)
    }

Plan: 6 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.
```

When I try to apply it though I get the following error:

```
module.aks-jx.azurerm_resource_group.cluster: Creating...
module.aks-jx.azurerm_resource_group.network: Creating...

Error: Error checking for presence of existing resource group: resources.GroupsClient#Get: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client '***@***' with object id '6bf2e421-2794-472e-a74f-29676d011bde' does not have authorization to perform action 'Microsoft.Resources/subscriptions/resourcegroups/read' over scope '/subscriptions/0ee859ed-0f8b-45c0-b61c-011a254f5736/resourcegroups/tf-jx-pleasant-caribou' or the scope is invalid. If access was recently granted, please refresh your credentials."

  on ../../../work/terraform/terraform-azurerm-jx/main.tf line 38, in resource "azurerm_resource_group" "network":
  38: resource "azurerm_resource_group" "network" {

Error: Error checking for presence of existing resource group: resources.GroupsClient#Get: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client ''***@***' ' with object id '6bf2e421-2794-472e-a74f-29676d011bde' does not have authorization to perform action 'Microsoft.Resources/subscriptions/resourcegroups/read' over scope '/subscriptions/0ee859ed-0f8b-45c0-b61c-011a254f5736/resourcegroups/tf-jx-smooth-polliwog' or the scope is invalid. If access was recently granted, please refresh your credentials."
```

I am not sure what to make of this. This might be unrelated to your pull request, but a general problem of my Azure account setup and which privileges it has. @chrismellard have you seen this error before?

**Comment by hferentschik** [comment]
@chrismellard do you want to address any of the things mentioned above or shall we go ahead and merge? I am still not able to stand up a cluster, but I can see where this is going ;-)

**Comment by chrismellard** [comment]
@hferentschik Some of those exceptions - certainly the authorizationFailed ones would seem to indicate a lack of permissions on the subscription the azurerm provider is trying to create resource groups under. Worth confirming if your account (the one that `az` is logged in as) has Contributor permissions on the subscription. Happy for it to be merged. I'm working through `jx boot` currently and there are issues with this terraform module in terms of requirements output and probably some in cluster facets like namespaces and service accounts but these could be resolved as separate tickets

**Comment by hferentschik** [comment]
Let's use this as a stepping stone.

**Comment by helayoty** [comment]
@chrismellard  Thank you for kicking off the work again. I'm working on adding the msi support but I got the following error 

```Error: Invalid index

  on main.tf line , in module "dns":
  93:   resource_group_name      = azurerm_resource_group.dns[0].name
    |----------------
    | azurerm_resource_group.dns is empty tuple

The given key does not identify an element in this collection value.
```

The issue fixed when I remove the count from dns rg creation. 

Do you have any idea why I'm facing this behavior?

**Pull request merged**
