### PR TITLE
feat: aadpod_identity

### PR DESCRIPTION
**Pull request by chrismellard**

### CODE REVIEW

**Comment by gregberns** [comment]
@chrismellard Just saw you were working on this and I just got this working last week. Here's the module I got working... maybe it will be helpful.

```
variable "environment" {
  type        = string
  description = "runtime environment: prod, dev"
}

variable "cluster_name" {
  type        = string
  description = "aks cluster name"
}

variable "cluster_location" {
  type        = string
  description = "aks cluster location"
}

variable "cluster_resource_group" {
  type        = string
  description = "aks cluster resource group"
}

variable "cluster_nodes_resource_group" {
  type        = string
  description = "aks cluster nodes resource group"
}

data "azurerm_resource_group" "nodes_rg" {
  name = var.cluster_nodes_resource_group
}

data "azurerm_kubernetes_cluster" "cluster" {
  name                = var.cluster_name
  resource_group_name = var.cluster_resource_group
}

### Built based off this
## https://github.com/Azure/aad-pod-identity/blob/master/hack/role-assignment.sh

# These role assignments are fot the AAD service
resource "azurerm_role_assignment" "mio" {
  scope                = data.azurerm_resource_group.nodes_rg.id
  role_definition_name = "Managed Identity Operator"
  principal_id         = data.azurerm_kubernetes_cluster.cluster.kubelet_identity[0].object_id
}

resource "azurerm_role_assignment" "vmc_nodes" {
  scope                = data.azurerm_resource_group.nodes_rg.id
  role_definition_name = "Virtual Machine Contributor"
  principal_id         = data.azurerm_kubernetes_cluster.cluster.kubelet_identity[0].object_id
}

############## Database ##############

resource "azurerm_user_assigned_identity" "mi" {
  name                = "mi-app-k8s-db-${var.environment}-${var.cluster_location}"
  resource_group_name = var.cluster_nodes_resource_group
  location            = var.cluster_location
}
resource "azurerm_role_assignment" "mi_reader" {
  scope                = data.azurerm_resource_group.nodes_rg.id
  role_definition_name = "Reader"
  principal_id         = azurerm_user_assigned_identity.mi.principal_id
}

######################################

############# Key Vault ##############

resource "azurerm_user_assigned_identity" "kv" {
  name                = "mi-app-k8s-kv-${var.environment}-${var.cluster_location}"
  resource_group_name = var.cluster_nodes_resource_group
  location            = var.cluster_location
}
resource "azurerm_role_assignment" "kv" {
  scope                = data.azurerm_resource_group.nodes_rg.id
  role_definition_name = "Reader"
  principal_id         = azurerm_user_assigned_identity.kv.principal_id
}

######################################

# https://github.com/Azure/aad-pod-identity/tree/master/charts/aad-pod-identity
resource "helm_release" "identity" {
  name       = "aad-pod-identity"
  chart      = "https://github.com/Azure/aad-pod-identity/raw/master/charts/aad-pod-identity-2.0.2.tgz"
  version    = "2.0.2"
  values = [
    <<EOF
azureIdentities:
##### Database #####
- name: "${azurerm_user_assigned_identity.mi.name}"
  type: 0
  resourceID: "${azurerm_user_assigned_identity.mi.id}"
  clientID: "${azurerm_user_assigned_identity.mi.client_id}"
  binding:
    name: "${azurerm_user_assigned_identity.mi.name}-binding"
    selector: "${azurerm_user_assigned_identity.mi.name}"
##### Key Vault #####
- name: "${azurerm_user_assigned_identity.kv.name}"
  type: 0
  resourceID: "${azurerm_user_assigned_identity.kv.id}"
  clientID: "${azurerm_user_assigned_identity.kv.client_id}"
  binding:
    name: "${azurerm_user_assigned_identity.kv.name}-binding"
    selector: "${azurerm_user_assigned_identity.kv.name}"
EOF
  ]
}

output "key_vault_mi_id" {
  value = azurerm_user_assigned_identity.kv.id
}

output "key_vault_mi_principal_id" {
  value = azurerm_user_assigned_identity.kv.principal_id
}

```

**Comment by chrismellard** [comment]
Thanks @gregberns - only issue I'm battling is a flaky Kubernetes-alpha provider as I want to use this  to put the CRDs in to a variety of namespaces. Is that possible  when you specify them inline in the chart values?

**Comment by gregberns** [comment]
@chrismellard sorry, not sure I can help with that (I'm still only on month 1 or 2 of k8s). I did have some issues working across namespaces - but I think that was an initial config issue. And I haven't used the k8s terraform provider yet.
I think the only thing I played with in the values of this helm chart are supplying the multiple managed identities, which my DBA wants so different pods can use different identities. Not sure if thats something commonly desired or if there's a better way to go about it.

**Comment by chrismellard** [comment]
I think multiple identities is the way to go to ensure principal of least privilege for identities. Putting these identities in the chart values will solve my issues. Just feels like this breaks module encapsulation having to tell a chart about all the identities I ever care about forever more. Think I know where the issue is in the Kubernetes-alpha  provider so I might open a PR and fix up there.

**Comment by chrismellard** [comment]
Or not. Someone else already working on it - https://github.com/hashicorp/terraform-provider-kubernetes-alpha/pull/41. I'll use chart values for now I guess to make progress and revisit pending this PR.

**Comment by gregberns** [comment]
100% agree. Thanks for passing that on, that’ll be a big help. And thanks
for all you work on this project, it’s been critical in getting my cluster
stood up.

**Comment by chrismellard** [comment]
Resolves #4

**Pull request merged**
